alter table AdultVisitor_include rename to adult;
alter table YoungVisitor_include_isGuradedBy rename to young;
alter table adult rename column visitorname to aname;
alter table young rename column youngvisitorname to yname;
alter table adult rename column groupid to gid;
alter table maintenancefacility rename to facility;
alter table young rename column youngGroupID to yGID;
alter table young rename column adultVisitorName to aName;
alter table young rename column adultGroupID to aGID;
alter table ATTRACTIONS_INSEPECT_AND_DETERMINES_STATUS1 rename to attraction;
alter table ATTRACTIONS_INSEPECT_AND_DETERMINES_STATUS2 rename to aCapacity;
alter table ENTERTAINMENTS_DETERMIN_STATUS_AND_ARRANGE_TIMES1 rename to entertainment;
alter table ENTERTAINMENTS_DETERMIN_STATUS_AND_ARRANGE_TIMES2 rename to eCategory;
alter table RESERVATION_LINKEDTO_MANAGEDBY rename to reservation;
alter table repair rename column repaire_date to rdate;
